name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: |
        wget https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz -O shchk.tar.xz
        tar xvf shchk.tar.xz
        export PATH=$(pwd)/shellcheck-latest:$PATH
        tests/main.sh
